# 程式碼審查提示詞
# Code Review Prompt

trigger: ":code-review"
label: "程式碼審查"
description: "請 AI 審查程式碼並提供改進建議"

prompt: |
  請審查以下程式碼，並提供詳細的回饋：

  1. **程式碼品質**：是否遵循最佳實踐？
  2. **潛在問題**：是否有 bug 或安全漏洞？
  3. **效能**：是否有效能改進空間？
  4. **可讀性**：命名是否清晰？結構是否合理？
  5. **建議**：具體的改進方案

  程式碼：
  ```
  {{code}}
  ```
