# 程式碼解釋提示詞
# Code Explanation Prompt

trigger: ":explaincode"
label: "解釋程式碼"
description: "請 AI 詳細解釋程式碼的功能與邏輯"

prompt: |
  請詳細解釋以下程式碼：

  1. **整體功能**：這段程式碼的主要目的是什麼？
  2. **逐行解析**：每一段程式碼在做什麼？
  3. **關鍵概念**：使用了哪些重要的程式設計概念或模式？
  4. **資料流**：資料是如何流動與轉換的？
  5. **使用情境**：這段程式碼通常在什麼情況下使用？

  程式碼：
  ```
  {{code}}
  ```

form_fields:
  code:
    multiline: true

