# 修復 Bug 提示詞
# Fix Bug Prompt

trigger: ":fixbug"
label: "修復 Bug"
description: "請 AI 分析並修復程式碼中的錯誤"

prompt: |
  請幫我分析並修復這個 Bug：

  **錯誤描述**：
  {{error_description}}

  **錯誤訊息**（如有）：
  ```
  {{error_message}}
  ```

  **相關程式碼**：
  ```
  {{code}}
  ```

  請提供：
  1. **問題分析**：Bug 的根本原因是什麼？
  2. **修復方案**：完整的修復程式碼
  3. **預防措施**：如何避免類似問題再次發生？
  4. **測試建議**：如何驗證修復是否成功？

form_fields:
  error_description:
    multiline: true
  error_message:
    multiline: true
  code:
    multiline: true

