# 提示詞由 Issue #3 貢獻
# 貢獻者: @doggy8088

trigger: ":nbp"
label: "資訊圖表（專業風格）"
description: "生成一張專業風格的資訊圖表"

prompt: |
  Infographic, $|$ style, zh-tw language on text, cheerful, clean lines, simple shapes, 16:9 aspect ratio, professional, easy to understand, detailed, high resolution, soft lighting, (best quality, masterpiece)

  Negative prompt: ugly, deformed, noisy, blurry, low quality, bad anatomy, bad proportions, out of frame, text, watermark, signature

  Content:
  {{content}}

form_fields:
  content:
    multiline: true
