# 程式碼重構提示詞
# Code Refactoring Prompt

trigger: ":refactor"
label: "程式碼重構"
description: "請 AI 重構程式碼以提升品質"

prompt: |
  請重構以下程式碼，目標是：

  1. **提升可讀性**：讓程式碼更容易理解
  2. **減少重複**：消除重複的程式碼（DRY 原則）
  3. **改善結構**：使用適當的設計模式
  4. **優化效能**：在不影響可讀性的前提下優化
  5. **加強型別安全**：如適用，加入型別註解

  請提供：
  - 重構後的完整程式碼
  - 每個改動的說明
  - 重構前後的比較

  原始程式碼：
  ```
  {{code}}
  ```
