# 摘要提示詞
# Summarize Prompt

trigger: ":summarize"
label: "內容摘要"
description: "請 AI 摘要長篇內容"

prompt: |
  請為以下內容提供摘要：

  要求：
  1. **摘要長度**：約 {{length|200}} 字
  2. **重點提取**：列出 3-5 個關鍵要點
  3. **結構清晰**：使用條列式呈現
  4. **保持客觀**：忠實反映原文內容

  內容：
  {{content}}

form_fields:
  content:
    multiline: true
