# 撰寫文件提示詞
# Write Documentation Prompt

trigger: ":write-doc"
label: "撰寫文件"
description: "請 AI 為程式碼撰寫技術文件"

prompt: |
  請為以下程式碼撰寫完整的技術文件：

  要求：
  1. **概述**：簡要說明功能與用途
  2. **安裝/設定**：如何開始使用
  3. **API 說明**：
     - 函數/方法簽章
     - 參數說明（型別、必填/選填、預設值）
     - 回傳值說明
  4. **使用範例**：提供實際的程式碼範例
  5. **注意事項**：使用上的限制或注意點

  程式碼：
  ```
  {{code}}
  ```

form_fields:
  code:
    multiline: true
